# Generated by Django 2.1 on 2018-08-15 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gugun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gugun', models.CharField(max_length=10, verbose_name='구/군')),
            ],
            options={
                'verbose_name_plural': '구/군 테이블',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='프로젝트 명')),
                ('type', models.CharField(choices=[('pro', '프로'), ('under', '언더'), ('both', '상관없음')], max_length=10, verbose_name='성우타입')),
                ('cost', models.PositiveIntegerField(verbose_name='예상금액')),
                ('period', models.PositiveIntegerField(verbose_name='예상기간')),
                ('deadline', models.DateField(verbose_name='마감기간')),
                ('contant', models.TextField(verbose_name='프로젝트 내용')),
                ('start_at', models.DateField(verbose_name='예상 시작일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('gugun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Gugun', verbose_name='위치')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name_plural': '프로젝트 테이블',
            },
        ),
        migrations.CreateModel(
            name='ProjectApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='지원금액')),
                ('period', models.PositiveIntegerField(verbose_name='지원기간')),
                ('content', models.TextField(verbose_name='지원내용')),
                ('voice', models.FileField(upload_to='', verbose_name='녹음파일')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Project', verbose_name='프로젝트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name_plural': '프로젝트 지원 테이블',
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name_plural': '태그 테이블',
            },
        ),
        migrations.CreateModel(
            name='Sido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(max_length=10, verbose_name='시/도')),
            ],
            options={
                'verbose_name_plural': '시/도 테이블',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='태그명')),
            ],
            options={
                'verbose_name_plural': '태그 테이블',
            },
        ),
        migrations.AddField(
            model_name='projecttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Tag', verbose_name='태그'),
        ),
        migrations.AddField(
            model_name='gugun',
            name='sido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Sido', verbose_name='시/도'),
        ),
    ]
