# Generated by Django 2.1 on 2018-08-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttag',
            options={'verbose_name_plural': '프로젝트별 태그 테이블'},
        ),
        migrations.AddField(
            model_name='project',
            name='gender',
            field=models.CharField(choices=[('male', '남자'), ('female', '여자'), ('both', '상관없음')], default=1, max_length=5, verbose_name='성별'),
            preserve_default=False,
        ),
    ]
