# Generated by Django 2.1 on 2018-08-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20180815_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gender',
            field=models.CharField(choices=[('male', '남자'), ('female', '여자'), ('both', '상관없음')], max_length=10, verbose_name='성별'),
        ),
    ]
