# Generated by Django 2.1 on 2018-08-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20180815_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name_plural': '프로젝트 테이블'},
        ),
        migrations.AlterField(
            model_name='project',
            name='gender',
            field=models.CharField(choices=[('male', '남자'), ('female', '여자'), ('both', '성별무관')], max_length=10, verbose_name='성별'),
        ),
    ]
