# Generated by Django 2.1 on 2018-08-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20180816_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contant',
            new_name='content',
        ),
    ]
