# Generated by Django 2.1 on 2018-08-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20180818_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(verbose_name='마감날짜'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gender',
            field=models.CharField(choices=[('both', '성별무관'), ('male', '남자'), ('female', '여자')], max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_at',
            field=models.DateField(verbose_name='예상 시작날짜'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('both', '상관없음'), ('pro', '프로'), ('under', '언더')], max_length=10, verbose_name='성우타입'),
        ),
    ]
